### ISSUE TITLE
ReferenceError: Elm is not defined

### ISSUE THREAD

**Issue by Mattnmoore** [tightenco/laravel-elm#4]
I'm getting the following error when I try to serve a basic Elm application created from this package.

`ReferenceError: Elm is not defined`

I'm using the laravel-elm javascript package and mix using the following config:

```
const mix = require('laravel-mix');
const elm = require('laravel-elm');

mix.js('resources/js/app.js', 'public/js')
    .sass('resources/sass/app.scss', 'public/css')
    .then(elm);
```

And the route:
```
use Tightenco\Elm\Elm;
Route::get('/', function() {
    return view('home', [
        'Example' => Elm::make('Example'),
    ]);
});
```

And the view:
```
{!! $Example !!}
```

**Comment by Mattnmoore** [comment]
Whoops! Didn't realize you have to manually include

`<script src="/js/elm.js"></script>`

Closing the issue as it works properly now.

**Comment by loganhenson** [comment]
Ah yes, this should probably be included in the readme, thanks!
