### ISSUE TITLE
Version output of elm.js

### ISSUE THREAD

**Issue by joshhornby** [tightenco/laravel-elm#5]
Hi,

Is it possible to version the output of `elm.js`?

According to the docs you include the script like `<script src="/js/elm.js"></script>` but it would be nice to be able to `<script src="{{mix (/js/elm.js) }} "></script>`

**Comment by loganhenson** [comment]
There is likely a more elegant way, but I haven't looked into it much yet. I believe you can use the mix manifest directly to add it though (e.g. in production use versioning):

```
    .then(elm)
    .then(() => {
        const manifest = new Manifest()

        if (mix.inProduction()) {
            manifest.hash(new File('/js/elm.js').pathFromPublic()).refresh()
            manifest.hash(new File('/js/app.js').pathFromPublic()).refresh()
            manifest.hash(new File('/css/app.css').pathFromPublic()).refresh()
        } else {
            manifest.add('/js/elm.js')
            manifest.add('/js/app.js')
            manifest.add('/css/app.css')
        }

        manifest.refresh()
    })
```

**Comment by joshhornby** [comment]
Hi @loganhenson 

This above code snippet doesn't seem to work, I've simplified it to:

```
    .then(elm)
    .then(() => {
        const manifest = new Manifest();

        manifest.hash(new File('public/js/elm.js')).refresh();

        manifest.refresh();
    })
```

But the `mix-manifest.json` never includes `elm.js`.

**Comment by loganhenson** [comment]
Have you tried with `new File('/js/elm.js')` ?

**Comment by joshhornby** [comment]
Yeh, if I `console.log(file)` inside the `hash` method `elm.js` never get's called..

**Comment by loganhenson** [comment]
@joshhornby with the latest 4.0 version this should be a much more seamless experience
